### ISSUE TITLE
没找到1对n关联查询结果映射的相关文档

### ISSUE THREAD

**Issue by zohar-soul** [drinkjava2/jSqlBox#4]
能问下在哪吗?
就是比如映射成这样的结构

prIvate long id;
private List<Role> roles;

**Comment by drinkjava2** [comment]
抱歉才看到你这个贴，一般我只看码云上有没有issue，把github作为临时工作目录。
关于jSqlBox的实体关联查询，文档请参见[这里](https://gitee.com/drinkjava2/jsqlbox/wikis/pages?sort_id=453893&doc_id=92178)
示例请参见[这里](https://gitee.com/drinkjava2/jsqlbox/blob/master/core/src/test/java/com/github/drinkjava2/jsqlbox/function/entitynet/EntityNetTest.java)

**Comment by zohar-soul** [comment]
好的 非常感谢
